permissions: write-all

on:
  workflow_dispatch:
    inputs:
      caution:
        required: false
        type: string
        description: このワークフローを手動で実行しないでください<br/>https://github.com/
        default: テキストボックスの値は無視されます
jobs:
  call_reusable_workflow1:
    uses: ./.github/workflows/sub0.yml
    with:
      root_job_name: call_reusable_workflow1

  call_reusable_workflow2:
    uses: ./.github/workflows/sub0.yml
    with:
      root_job_name: call_reusable_workflow2
