permissions: write-all

on:
  workflow_dispatch:
    inputs:
      caution:
        required: false
        type: string
        description: あのイーハトーヴォのすきとおった風
        default: 夏でも底に冷たさをもつ青いそら

jobs:
  call_reusable_workflow1:
    uses: ./.github/workflows/sub0.yml
    with:
      root_job_name: call_reusable_workflow1

  call_reusable_workflow2:
    uses: ./.github/workflows/sub0.yml
    with:
      root_job_name: call_reusable_workflow2
