permissions: write-all

on:
  workflow_dispatch:
    inputs:
      caution:
        required: false
        type: string
        description: このワークフローを手動で実行しないでください. https://www.notion.so/11111111111111111111111111111111
        default: a
jobs:
  call_reusable_workflow1:
    uses: ./.github/workflows/sub0.yml
    with:
      root_job_name: call_reusable_workflow1

  call_reusable_workflow2:
    uses: ./.github/workflows/sub0.yml
    with:
      root_job_name: call_reusable_workflow2
