on:
  workflow_call:

jobs:
  example_job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Display Calling Job ID
        run: echo "The calling job name is ${{ github.event.workflow_call.inputs.job_name }}"

      - name: touch

        run: |
          mkdir -p /tmp/out
          touch /tmp/out/$(date +%s).txt

      - name: Upload tags
        uses: actions/upload-artifact@v4
        with:
          name: tags_a_b
          path: /tmp/out/*
          if-no-files-found: error
          retention-days: 1

      - name: Download tags
        uses: actions/download-artifact@v4
        with:
          path: /tmp/downloads/
          pattern: tags_*
          merge-multiple: true
