permissions: write-all

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      root_job_name:
        required: false
        type: string

jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      root_job_name: ${{ steps.root_job_name.outputs.root_job_name }}
    steps:
      - name: Set Root Job Name
        id: root_job_name
        run: |
          if [ -z "${{ inputs.root_job_name }}" ]; then
            echo "root_job_name=default" >> $GITHUB_OUTPUT
          else
            echo "root_job_name=${{ inputs.root_job_name }}" >> $GITHUB_OUTPUT
          fi

  call_reusable_workflow1:
    needs: init
    uses: ./.github/workflows/sub.yml
    with:
      parent_name: ${{ needs.init.outputs.root_job_name }}
